console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'red'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'green'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 1000

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }}'
    foreground = 'black'
    type = 'time'
    style = 'plain'
    
    [blocks.segments.properties]
      time_format = "15:04"
